### ISSUE TITLE
Format example

### ISSUE THREAD

**Issue by TonisOrmisson** [iddqdidkfa/yii2-knob#2]
Can you give an example on how to use the format option?
thanks!

**Comment by iddqdidkfa** [comment]
Hi. Sorry for long response. This package is not actually maintained and jQuery Knob plugin too. I do not have sandbox to check, but looks like format should be used something like this:
```
'knobOptions' => [
       'format' => new JsExpression("function(value) { return value + '%';  }")
 ],
```

**Comment by TonisOrmisson** [comment]
Thanks a lot!
